config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :orders, only: %i[new create] do
    collection do
      post :confirm
      get :complete
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inflow_source.rb
class InflowSource < ApplicationRecord
end

app/models/order.rb
require 'nkf'

class Order < ApplicationRecord
  TAX_RATE = 1.1

  belongs_to :payment_method
  has_many :order_inflow_sources
  has_many :inflow_sources, through: :order_inflow_sources
  has_many :order_products
  
  # 子テーブルのパラメーターも受け取る
  accepts_nested_attributes_for :order_products

  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, length: { maximum: 100 }, email_format: true
  validates :telephone, presence: true, length: { maximum: 11 }, numericality: { only_integer: true }
  validates :delivery_address, presence: true, length: { maximum: 100 }
  validates :payment_method_id, presence: true
  validates :other_comment, length: { maximum: 1_000 }
  # ラジオボタンの場合
  validates :direct_mail_enabled, inclusion: { in: [true, false], message: 'について選択してください。' }
  after_initialize :format_telephone
  after_initialize :format_email

  def total_price
    # (order_products.map(&:order_price).sum * TAX_RATE).ceil
    (BigDecimal(order_products.map(&:order_price).sum.to_s) * BigDecimal(TAX_RATE.to_s)).ceil
  end

  private

  def format_telephone
    return if telephone.blank?

    self.telephone = telephone.tr('０-９', '0-9').delete('^0-9')
  end

  def format_email
    return if email.blank?

    self.email = NKF.nkf('-w -Z4', email)
  end
end

app/models/order_inflow_source.rb
class  OrderInflowSource < ApplicationRecord
  belongs_to :order
  belongs_to :inflow_source
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: { in: 1..20 }

  delegate :name, :name_and_price_text, to: :product

  def order_price
    product.price * quantity
  end
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  class << self
    def selectable_methods
      all.map { |method| [method.name, method.id] }
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  class << self
    def selectable_products
      all.map { |product| [ActiveDecorator::Decorator.instance.decorate(product).name_and_price_text, product.id] }
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @order.order_products.build
  end

  def confirm
    @order = Order.new(order_params)
    if params.key?(:add_product)
      @order.order_products << OrderProduct.new
      return render :new
    end
    if params.key?(:delete_product)
      filter_order_products
      return render :new
    end

    return render :new if @order.invalid?
  end

  def create
    @order = Order.new(order_params)
    return render :new if params[:button] == 'back'
    
    if @order.save
      # 非同期処理
      OrderMailerJob.perform_later(@order.id)
      session[:order_id] = @order.id
      return redirect_to complete_orders_url 
    end
    render :confirm
  end

  def complete
    @order = Order.find_by(id: session[:order_id])
    return redirect_to new_order_url if @order.blank?

    session[:order_id] = nil
  end

  private

  def order_params
    params
      .require(:order)
      .permit(:name,
              :email,
              :telephone,
              :delivery_address,
              :payment_method_id,
              :other_comment,
              :direct_mail_enabled,
              inflow_source_ids: [],
              order_products_attributes: %i[product_id quantity])
  
  end

  def filter_order_products
    @order.order_products = @order.order_products
                                  .reject
                                  .with_index { |_, index| index == params[:delete_product].to_i }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>注文フォーム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/complete.html.erb
<div class="container mt-3 mb-5">
  <h1 class="text-center mb-5">注文完了</h1>

  <div class="text-center mb5">
    <p>
      <%= @order.name %>様
      <br>
      ご注文ありがとうございました
      <br>
      商品の発送までしばらくお待ちください。
    </p>
  </div>
</div>

app/views/orders/confirm.html.erb
<div class='container mt-3 mb-5'>
  <h1 class='text-center mb-5'>注文内容の確認</h1>
  <div class="col-md-6 mx-auto mb-5">
    <p>以下の内容でよろしいでしょうか？</p>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.name') %>
      </div>
      <%= @order.name %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.email') %>
      </div>
      <%= @order.email %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.telephone') %>
      </div>
      <%= @order.telephone %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.delivery_address') %>
      </div>
      <%= @order.delivery_address %>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.payment_method_id') %>
      </div>
      <%= @order.payment_method.name %>
    </div>

    <!-- 子テーブル -->
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.order_products') %>
      </div>
      <% @order.order_products.each do |order_product| %>
        <div class='border border-secondary border-1 rounded p-3 mb-3'>
          <div class="mb-3">
            <div class="form-label border-start border-primary border-2 ps-1">
              <%= t('activerecord.attributes.order_product.product_id') %>
            </div>
            <%= order_product.name_and_price_text %>
            <!-- 数量  -->
            <div class="form-label border-start border-primary border-2 ps-1">
              <%= t('activerecord.attributes.order_product.quantity') %>
            </div>
            <%= order_product.quantity %>
          </div>
        </div>
      <% end %>
      <span class="fs-5 fw-bold">合計金額: <%= number_to_currency(@order.total_price) %>(税込)</span>
    </div>
    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.other_comment') %>
      </div>
      <% if @order.other_comment.present? %>
        <%= simple_format(@order.other_comment) %>
      <% else %>
        <span class="text-secondary">(未記入)</span>
      <% end %>
    </div>

    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.direct_mail_enabled') %>
      </div>
      <%= @order.direct_mail_enabled_text %>
    </div>

    <div class="mb-3">
      <div class="form-label border-start border-primary border-4 ps-1">
        <%= t('activerecord.attributes.order.inflow_source_ids') %>
      </div>
      <%= @order.inflow_sources.map(&:name).join(', ') %>
    </div>
  </div>

  <%= form_for @order, url: orders_path do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :telephone %>
    <%= f.hidden_field :delivery_address %>
    <%= f.hidden_field :payment_method_id %>
    <%= f.hidden_field :other_comment %>
    <%= f.hidden_field :direct_mail_enabled %>
    <% @order.inflow_source_ids.each do |inflow_source_id| %>
      <%= hidden_field_tag 'order[inflow_source_ids][]', inflow_source_id %>
    <% end %>

    <%= f.fields_for :order_products do |pf| %>
      <%= pf.hidden_field :product_id %>
      <%= pf.hidden_field :quantity %>
    <% end %>


    <div class='d-grid col-md-6 mx-auto mb-3'>
      <%= f.button 'OK', class: 'btn btn-lg btn-primary' %>
    </div>
    <div class='d-grid col-md-6 mx-auto'>
      <%= f.button '戻る', value: 'back', class: 'btn btn-lg btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/orders/create.html.erb
<div class="container mt-3 mb-5">
  <h1 class="text-center mb-5">注文完了</h1>

  <div class="text-center mb5">
    <p>
      ご注文ありがとうございました
      <br>
      商品の発送までしばらくお待ちください。
    </p>
  </div>
</div>

app/views/orders/new.html.erb
<div class='container mt-3 mb-5'>
  <h1 class='text-center mb-5'>注文フォーム</h1>

  <%= form_for @order, url: confirm_orders_path do |f| %>
    <div class='col-md-6 mx-auto mb-5'>
      <div class='mb-3'>
        <%= f.label :name, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.text_field :name, size: 40, placeholder: 'サンプル太郎', class: 'form-control' %>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :name } %>
      </div>

      <div class='mb-3'>
        <%= f.label :email, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.text_field :email, size: 100, placeholder: 'sample@example.com', class: 'form-control' %>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :email } %>
      </div>

      <div class='mb-3'>
        <%= f.label :telephone, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.text_field :telephone, size: 40, placeholder: '0312345678', class: 'form-control' %>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :telephone } %>
      </div>

      <div class='mb-3'>
        <%= f.label :delivery_address, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.text_field :delivery_address, size: 40, placeholder: 'お届け先の住所をご入力ください。', class: 'form-control' %>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :delivery_address } %>
      </div>

      <div class="mb-3">
        <%= f.label :payment_method_id, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.select :payment_method_id, PaymentMethod.selectable_methods, { include_blank: true }, class: 'form-select' %>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :payment_method_id } %>
      </div>

      <!-- 子テーブル -->
      <div class="mb-3">
        <%= f.label :order_products, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.fields_for :order_products do |pf| %>
          <div class="border border-secondary border-1 rounded p-3 mb-3">
            <div class="mb-3">
              <%= pf.label :product_id, t('activerecord.attributes.order_product.product_id'), class: 'form-label border-start border-primary border-2 ps-1' %>
              <!-- <%= pf.label :product_id, t('activerecord.attributes.order_product.product_id'), class: 'form-label border-start border-primary border-2 ps-1' %> -->
              <%= pf.select :product_id, Product.selectable_products, { include_blank: true }, class: 'form-select' %>
              <%= render partial: 'shared/error_messages', locals: { record: pf.object, symbol: :product_id } %>
            </div>
            <!-- 数量 -->
            <div class="mb-3">
              <%= pf.label :quantity, t('activerecord.attributes.order_product.quantity'), class: 'form-label border-start border-primary border-2 ps-1' %>
              <%= pf.number_field :quantity, size: 4, placeholder: '数量', class: 'form-control' %>
              <%= render partial: 'shared/error_messages', locals: { record: pf.object, symbol: :quantity } %>
            </div>

            <% if @order.order_products.size > 1 %>
              <div class='d-grid d-md-flex justify-content-end'>
                <%= f.button '削除', name: 'delete_product', value: pf.index, class: 'btn btn-danger'%>
              </div>
            <% end %>
          </div>
        <% end %>
        <% if @order.order_products.size < 3 %>
          <%= f.button '商品を追加する', name: 'add_product', class: 'btn btn-primary'%>
        <% end %>
      </div>

      <div class="mb-3">
        <%= f.label :other_comment, class: 'form-label border-start border-primary border-4 ps-1' %>
        <%= f.text_area :other_comment, size: '60x6', placeholder: 'その他、ご要望がありましたらご入力ください。', class: 'form-control' %>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :other_comment } %>
      </div>  

      <div class="mb-3">
        <%= f.label :direct_mail_enabled, class: 'form-label border-start border-primary border-4 ps-1' %>
        <div class="mb-2 fs-6">*お得な情報満載のメールマガジンを配信しております。</div>
        <div class='form-check form-check-inline'>
          <label class='form-check-label'>
            <%= f.radio_button :direct_mail_enabled, false, class: 'form-check-input' %>
            配信は不要
          </label>
        </div>
        <div class='form-check form-check-inline'>
          <label class='form-check-label'>
            <%= f.radio_button :direct_mail_enabled, true, class: 'form-check-input' %>
            配信を希望する
          </label>
        </div>
        <%= render partial: 'shared/error_messages', locals: { record: @order, symbol: :direct_mail_enabled } %>
      </div>

      <div class="mb-5">
        <%= f.label :inflow_source_ids, class: 'form-label border-start border-primary border-4 ps-1' %>
        <div class="mb-2">*このサイトをどこでお知りになりましたか？(複数選択可)</div>
        <%= f.collection_check_boxes :inflow_source_ids, InflowSource.all, :id, :name do |inflow_source| %>
          <div class='form-check form-check-inline'>
            <%= inflow_source.label { inflow_source.check_box(class: 'form-check-input') + " #{inflow_source.text}" } %>
          </div>
        <% end %>
      </div>
    </div>

    <div class='d-grid col-md-6 mx-auto'>
      <%= f.submit '確認画面へ', class: 'btn btn-lg btn-primary' %> 
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<%= record.errors.full_messages_for(symbol).each do |message| %>
  <div class="text-danger">*<%= message %></div>
<% end %>